name: high-heels-ch
favicon: null
layout_spectrum: 0.4529570313170552
typography_spectrum: 0.7651445679366589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.46955218561924994
  lightness: 0.1809374471195042
  saturation: 0.14535039965994656
  rhythmicContrast: 0.8476505689322948
purpose: []
